# Generated by Django 5.2.6 on 2025-09-24 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subtema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtemas', to='docente.tema')),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('momento', models.CharField(choices=[('calentamiento', 'Calentamiento'), ('carro', 'Ejercicio Base - Carro'), ('juego', 'Ejercicio Base - Juego'), ('final', 'Juego Final')], max_length=50)),
                ('descripcion', models.TextField()),
                ('notas_pedagogicas', models.TextField(blank=True, null=True)),
                ('num_alumnos', models.IntegerField(default=1)),
                ('nivel', models.CharField(choices=[('iniciacion', 'Iniciación'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=50)),
                ('duracion', models.IntegerField(blank=True, help_text='Duración en minutos', null=True)),
                ('recursos', models.CharField(blank=True, max_length=200, null=True)),
                ('dificultad_min', models.IntegerField(default=1)),
                ('dificultad_max', models.IntegerField(default=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ejercicios/')),
                ('link', models.URLField(blank=True, null=True)),
                ('subtema1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejercicios_sub1', to='docente.subtema')),
                ('subtema2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejercicios_sub2', to='docente.subtema')),
                ('tema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='docente.tema')),
            ],
        ),
    ]
