# Generated by Django 5.2.6 on 2025-09-24 16:14

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0002_alter_subtema_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='dificultad_max',
            field=models.TextField(blank=True, help_text='Cómo hacer el ejercicio más fácil', null=True),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='dificultad_min',
            field=models.TextField(blank=True, help_text='Cómo hacer el ejercicio más difícil', null=True),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='nivel',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('iniciacion', 'Iniciación'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=50),
        ),
    ]
