# Generated by Django 5.2.6 on 2025-09-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0003_alter_ejercicio_dificultad_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='num_alumnos',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='num_alumnos_max',
            field=models.IntegerField(blank=True, help_text='Número máximo de alumnos (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='num_alumnos_min',
            field=models.IntegerField(default=1, help_text='Número mínimo de alumnos'),
        ),
    ]
