# Generated by Django 5.2.6 on 2025-09-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0004_remove_ejercicio_num_alumnos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='SinRaqueta',
            field=models.BooleanField(default=False, verbose_name='¿Se puede hacer sin raqueta?'),
        ),
    ]
