# Generated by Django 5.2.6 on 2025-09-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0005_ejercicio_sinraqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='momento',
            field=models.CharField(choices=[('calentamiento', 'Calentamiento'), ('saque', 'saque'), ('carro', 'Ejercicio Base - Carro'), ('juego', 'Ejercicio Base - Juego'), ('secundaria', 'pista secundaria'), ('final', 'Juego Final')], max_length=50),
        ),
    ]
