# Generated by Django 5.2.6 on 2025-09-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0006_alter_ejercicio_momento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ejercicio',
            old_name='SinRaqueta',
            new_name='sin_raqueta',
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='momento',
            field=models.CharField(choices=[('calentamiento', 'Calentamiento'), ('saque', 'Saque'), ('carro', 'Ejercicio Base - Carro'), ('juego', 'Ejercicio Base - Juego'), ('secundaria', 'Pista secundaria'), ('final', 'Juego Final')], max_length=50),
        ),
    ]
