# Generated by Django 5.2.6 on 2025-10-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0007_rename_sinraqueta_ejercicio_sin_raqueta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='ejercicios', to='docente.etiqueta'),
        ),
    ]
