# Generated by Django 5.2.6 on 2025-10-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0008_etiqueta_ejercicio_etiquetas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='etiquetas',
        ),
        migrations.DeleteModel(
            name='Etiqueta',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='etiquetas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
