# Generated by Django 5.2.6 on 2025-10-01 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0009_remove_ejercicio_etiquetas_delete_etiqueta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtema1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtemas1', to='docente.tema')),
            ],
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='subtema1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='docente.subtema1'),
        ),
        migrations.CreateModel(
            name='Subtema2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('subtema1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtemas2', to='docente.subtema1')),
            ],
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='subtema2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='docente.subtema2'),
        ),
        migrations.DeleteModel(
            name='Subtema',
        ),
    ]
